### PR TITLE
Fix namespace + autoloading issue. Fix example.

### PR DESCRIPTION
**Pull request by rmruano**

### CODE REVIEW

**Comment by pfefferle** [comment]
thanks!

**Comment by rmruano** [comment]
@pfefferle No problem! Perhaps a new release would be appropriate, the current one doesn't even have the namespace.

**Comment by pfefferle** [comment]
sure, but I have seen that the readme is not updated yet, can you update it too?

**Comment by rmruano** [comment]
Working on it, give me a few mins.

**Pull request merged**
